spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/logsense_db
    username: logsense_user
    password: vAyne27miNE

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  elasticsearch:
    uris: http://localhost:9200

kafka:
  address: localhost:9092
  groupId: logsense-group
  autoOffsetReset: earliest
  topic:
    ingestion: logIngestion


logsense:
  appender:
    enabled: true
    endpoint-url: http://localhost:8080/api/v1/logs
    service-name: my-new-project

server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /documentation
